# =========================================
# PROD PROFILE
# =========================================

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

# Production logging
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.root=INFO

# Disable white label errors
server.error.whitelabel.enabled=false

# Recommended Production Settings
server.forward-headers-strategy=framework

spring.jpa.open-in-view=false