# =========================================
# SERVER
# =========================================

server.port=${PORT:10000}
server.address=0.0.0.0
server.error.whitelabel.enabled=false

# =========================================
# DATABASE
# =========================================

spring.datasource.url=jdbc:mysql://localhost:3306/hr_dev_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=appuser
spring.datasource.password=apppassword

# =========================================
# JPA / HIBERNATE
# =========================================

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =========================================
# HIKARI OPTIMIZATION
# =========================================

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=30000

# =========================================
# LOGGING
# =========================================

logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR